### ISSUE TITLE
Recebo um erro e não sei o que é, por favor me ajude

### ISSUE THREAD

**Issue by ReDXeoL** [RafaelGodoyEbert/ViralCutter#1]
ERROR:
Por favor, insira o JSON no formato desejado:
{     "segments": [         {             "title": "ChatGPT Adorable Japanese Accent Challenge",             "start_time": "00:00:55",             "end_time": "00:01:34",             "description": "ChatGPT attempts to speak with a strong Japanese accent while asking viewers to subscribe in an adorable and playful way, showcasing its ability to adapt accents and entertain.",             "duration": 39,             "score": 85         },         {             "title": "Cute Voice Transformation: ChatGPT Goes Kawaii!",             "start_time": "00:02:32",             "end_time": "00:03:17",             "description": "ChatGPT transforms its voice into a soft, kawaii tone and performs an ultra-cute request, delighting viewers with its playful and adorable side.",             "duration": 45,             "score": 90         },         {             "title": "The Future of AI: Chatting with Machines Like Friends",             "start_time": "00:06:27",             "end_time": "00:07:00",             "description": "A reflection on the future of AI-human interaction, where chatting with machines like friends will be completely normal, creating a thought-provoking moment for viewers.",             "duration": 33,             "score": 75         }     ] }
Segmentos virais salvos em tmp/viral_segments.txt
Processing segment 1/3
Start time: 00:00:55, Duration: 39 seconds
Executing command: ffmpeg -y -ss 00:00:55 -i tmp/input_video.mp4 -t 39 -c:v h264_nvenc -preset p1 -b:v 5M -c:a aac -b:a 128k tmp/output000_original_scale.mp4
Generated segment: output000_original_scale.mp4, Size: 24359486 bytes

==================================================

Processing segment 2/3
Start time: 00:02:32, Duration: 45 seconds
Executing command: ffmpeg -y -ss 00:02:32 -i tmp/input_video.mp4 -t 45 -c:v h264_nvenc -preset p1 -b:v 5M -c:a aac -b:a 128k tmp/output001_original_scale.mp4
Generated segment: output001_original_scale.mp4, Size: 27940849 bytes

==================================================

Processing segment 3/3
Start time: 00:06:27, Duration: 33 seconds
Executing command: ffmpeg -y -ss 00:06:27 -i tmp/input_video.mp4 -t 33 -c:v h264_nvenc -preset p1 -b:v 5M -c:a aac -b:a 128k tmp/output002_original_scale.mp4
Generated segment: output002_original_scale.mp4, Size: 19931166 bytes

==================================================

---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
[<ipython-input-2-22a51f8efabf>](https://localhost:8080/#) in <cell line: 156>()
    167 
    168     cut_segments.cut(viral_segments)
--> 169     edit_video.edit()
    170 
    171     if burn_subtitles_option:

[/content/ViralCutter/scripts/edit_video.py](https://localhost:8080/#) in edit()
    121 
    122     cap.release()
--> 123     cv2.destroyAllWindows()
    124 
    125 

error: OpenCV(4.10.0) /io/opencv/modules/highgui/src/window.cpp:1295: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

**Comment by ReDXeoL** [comment]
Eu baixei e ele roda localmente e se funcionou, consegui os videoclipes
Não sei por que recebo esse erro no colab ...

![image](https://github.com/user-attachments/assets/6e676593-a1c5-4dce-8748-ee632e793df3)

**Comment by ReDXeoL** [comment]
Fiz funcionar no Colab comentando a linha que descreve o erro: #cv2.destroyAllWindows()

**Comment by RafaelGodoyEbert** [comment]
Como já descobriu como corrigir, vou fechar a Issue, caso tiver mais dúvidas, sinta-se à vontade de chamar na comunidade do Discord ou abrir uma nova Issue.

Reparei que é problema quando tem duas faces dividindo a tela, em breve vou aprimorar o código e removo esse detalhe. Ficaria feliz se pudesse relatar mais detalhes em nossa comunidade sobre quais dos colabs você usou e qual configuração usou.
